/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class progamcapcus extends javax.swing.JFrame {

    /**
     * Creates new form progamcapcus
     */
    public progamcapcus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p = new javax.swing.JTextField();
        l = new javax.swing.JTextField();
        t = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tulangrusuku = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jari = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rt = new javax.swing.JTextField();
        tinggikerucut = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setText("PANJANG");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 60, 30);

        jLabel3.setText("LEBAR");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 99, 60, 30);

        jLabel4.setText("TINGGI");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 154, 50, 30);
        jPanel1.add(p);
        p.setBounds(110, 50, 110, 30);
        jPanel1.add(l);
        l.setBounds(110, 100, 110, 30);
        jPanel1.add(t);
        t.setBounds(110, 150, 110, 30);

        jButton1.setText("HITUNG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 230, 80, 30);

        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 160, 40, 20);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(260, 110, 20, 20);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(260, 60, 20, 20);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Pictures\\220px-Balok.JPG")); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(230, 80, 400, 300);

        jTabbedPane1.addTab("BALOK", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setText("MASUKAN RUSUK ");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 50, 140, 30);
        jPanel2.add(tulangrusuku);
        tulangrusuku.setBounds(20, 80, 190, 30);

        jButton2.setText("VOLUME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(60, 150, 90, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Pictures\\kubus1.png")); // NOI18N
        jPanel2.add(jLabel16);
        jLabel16.setBounds(130, 0, 320, 310);

        jTabbedPane1.addTab("KUBUS", jPanel2);

        jPanel3.setLayout(null);

        jLabel9.setText("MASUKAN JARI - JARI ");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 40, 150, 40);

        jari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jariActionPerformed(evt);
            }
        });
        jPanel3.add(jari);
        jari.setBounds(30, 80, 190, 30);

        jLabel10.setText("CM");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(250, 80, 50, 30);

        jButton3.setText("VOLUME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(50, 130, 80, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Pictures\\bolaruang.jpg")); // NOI18N
        jPanel3.add(jLabel18);
        jLabel18.setBounds(230, 110, 200, 190);

        jTabbedPane1.addTab("BOLA", jPanel3);

        jPanel4.setLayout(null);

        jLabel11.setText("MASUKAN JARI-JARI ");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(20, 33, 120, 27);

        jLabel12.setText("MASUKAN TINGGI");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(20, 110, 110, 30);
        jPanel4.add(rt);
        rt.setBounds(160, 40, 120, 30);
        jPanel4.add(tinggikerucut);
        tinggikerucut.setBounds(160, 110, 120, 30);

        jButton4.setText("VOLUME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(100, 190, 80, 40);

        jLabel13.setText("cm");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(300, 120, 20, 20);

        jLabel14.setText("cm");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(300, 40, 20, 20);

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Pictures\\220px-Kerucut.JPG")); // NOI18N
        jPanel4.add(jLabel17);
        jLabel17.setBounds(220, -10, 280, 340);

        jTabbedPane1.addTab("KERUCUT", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(31, 108, 450, 330);

        jLabel1.setFont(new java.awt.Font("Trajan Pro 3", 3, 24)); // NOI18N
        jLabel1.setText("APLIKASI MENGHITUNG VOLUME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 530, 60);

        setBounds(0, 0, 544, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void jariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int panjang , lebar , tinggi , hasil;
        panjang = Integer.parseInt(p.getText());
        lebar= Integer.parseInt(l.getText());
        tinggi = Integer.parseInt(t.getText());
        hasil = panjang *lebar *tinggi ;
        
        try {
            JOptionPane.showMessageDialog(null , "Volume Balok adalah : "+hasil , "balok",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
             JOptionPane.showMessageDialog(null , "error :"+e,"Gagal" , JOptionPane.WARNING_MESSAGE);
             }       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int sisi , hasil ;
        sisi = Integer.parseInt(tulangrusuku.getText());
        hasil = sisi * sisi*sisi ;
        
        try {
            JOptionPane.showMessageDialog(null , "Volume Kubus adalah : "+hasil , "kubus",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
             JOptionPane.showMessageDialog(null , "error :"+e,"Gagal" , JOptionPane.WARNING_MESSAGE);
             }       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        float r , hasil ;
        r = Integer.parseInt(jari.getText());
        
        hasil = (float) (4/3 *3.14 *r*r*r);
        
        try {
            JOptionPane.showMessageDialog(null , "Volume Bola adalah  : "+hasil , "Bola",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
             JOptionPane.showMessageDialog(null , "error :"+e,"Gagal" , JOptionPane.WARNING_MESSAGE);
             }       
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        double ibujari , hasil1;
        double tinggi ;
        ibujari = Integer.parseInt(rt.getText());
        tinggi = Integer.parseInt(tinggikerucut.getText());
//        hasil1 = (1/3 * 3.14 * ibujari* ibujari * tinggi);
        hasil1 = Math.PI * ibujari* ibujari * tinggi *0.3;
        try {
            JOptionPane.showMessageDialog(null , "Volume Kerucut adalah : "+hasil1 , "Kerucut",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
             JOptionPane.showMessageDialog(null , "error :"+e,"Gagal" , JOptionPane.WARNING_MESSAGE);
             }       
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(progamcapcus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(progamcapcus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(progamcapcus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(progamcapcus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new progamcapcus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jari;
    private javax.swing.JTextField l;
    private javax.swing.JTextField p;
    private javax.swing.JTextField rt;
    private javax.swing.JTextField t;
    private javax.swing.JTextField tinggikerucut;
    private javax.swing.JTextField tulangrusuku;
    // End of variables declaration//GEN-END:variables
}
