/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

/**
 *
 * @author acer
 */
public class tugaspakzakaria extends javax.swing.JFrame {

    /**
     * Creates new form tugaspakzakaria
     */
    public tugaspakzakaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ctd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ctb = new javax.swing.JButton();
        bd = new javax.swing.JTextField();
        bb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ctd.setFont(new java.awt.Font("Square721 Cn BT", 1, 12)); // NOI18N
        ctd.setText("Convert to Desimal ");
        ctd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctdActionPerformed(evt);
            }
        });
        getContentPane().add(ctd);
        ctd.setBounds(50, 120, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setText("Bilangan Desimal ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 40, 170, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Bilangan Biner");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 180, 140, 40);

        ctb.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        ctb.setText("Convert to Biner");
        getContentPane().add(ctb);
        ctb.setBounds(240, 120, 130, 30);
        getContentPane().add(bd);
        bd.setBounds(210, 50, 180, 30);
        getContentPane().add(bb);
        bb.setBounds(210, 190, 180, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Pictures\\Doremon\\68543881-doraemon-wallpapers.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-140, -170, 600, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctdActionPerformed
        
        double bil1  ;
        bil1 = Double.parseDouble(bd.getText());
        String bil2 ="";
    }//GEN-LAST:event_ctdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugaspakzakaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugaspakzakaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugaspakzakaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugaspakzakaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugaspakzakaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bb;
    private javax.swing.JTextField bd;
    private javax.swing.JButton ctb;
    private javax.swing.JButton ctd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
